export {Home} from "./home/home"
export {LikePage} from "./likedpage/likepage"
export {WatchLaterPage} from "./watchlaterpage/watchlater"
export{HistoryPage} from "./historypage/history"
export {Playlist} from "./playlistpage/playlist"
export{Login} from "./Auth/login/login"
export {Signup} from "./Auth/signup/signup"
export {LandingPage} from "./landingpage/Landing"
export {Error404} from "./Error404/Error404"
export {SingleVideo} from "./SingleVideo/SingleVideo"